// build.js — Script de build para deploy na Vercel
// Copia todos os arquivos estáticos e gera config a partir de env vars
import fs from 'fs';
import path from 'path';

const DIST_DIR = 'dist';
const SRC_DIR = '.';

// Pastas/padrões para copiar
const ITEMS_TO_COPY = [
    'index.html',
    'taro2.html',
    'login.html',
    'dashboard.html',
    'dna.html',
    'numerologia.html',
    'hawkins.html',
    'bovis.html',
    'cursos.html',
    'curso-player.html',
    'mestres.html',
    'js/',
    'css/',
    'assets/'
];

// Limpa dist/
if (fs.existsSync(DIST_DIR)) {
    fs.rmSync(DIST_DIR, { recursive: true });
}
fs.mkdirSync(DIST_DIR, { recursive: true });

// Copia arquivos
for (const item of ITEMS_TO_COPY) {
    const srcPath = path.join(SRC_DIR, item);
    const destPath = path.join(DIST_DIR, item);

    if (!fs.existsSync(srcPath)) {
        console.log(`⚠️  Aviso: ${item} não encontrado, pulando.`);
        continue;
    }

    const stat = fs.statSync(srcPath);
    if (stat.isDirectory()) {
        fs.cpSync(srcPath, destPath, { recursive: true, filter: (src) => {
            // Não copia node_modules, .env, etc.
            const name = path.basename(src);
            return !name.startsWith('.') && name !== 'node_modules' && name !== 'dist';
        }});
        console.log(`📁 Copiando pasta: ${item}`);
    } else {
        fs.mkdirSync(path.dirname(destPath), { recursive: true });
        fs.copyFileSync(srcPath, destPath);
        console.log(`📄 Copiando: ${item}`);
    }
}

// Gera env-config.js a partir das variáveis de ambiente da Vercel
const envVars = {
    VITE_SUPABASE_URL: process.env.VITE_SUPABASE_URL || '',
    VITE_SUPABASE_ANON_KEY: process.env.VITE_SUPABASE_ANON_KEY || '',
    VITE_OPENROUTER_API_KEY: process.env.VITE_OPENROUTER_API_KEY || '',
    VITE_OPENROUTER_MODEL: process.env.VITE_OPENROUTER_MODEL || 'deepseek/deepseek-chat-v4-0724'
};

const envConfigContent = `// Generated by build.js — Config injected from Vercel env vars
window.__SUPABASE_URL__ = ${JSON.stringify(envVars.VITE_SUPABASE_URL)};
window.__SUPABASE_ANON_KEY__ = ${JSON.stringify(envVars.VITE_SUPABASE_ANON_KEY)};
window.__OPENROUTER_API_KEY__ = ${JSON.stringify(envVars.VITE_OPENROUTER_API_KEY)};
window.__OPENROUTER_MODEL__ = ${JSON.stringify(envVars.VITE_OPENROUTER_MODEL)};
`;

fs.writeFileSync(path.join(DIST_DIR, 'js', 'env-config.js'), envConfigContent);
console.log('✅ Gerado: js/env-config.js com variáveis de ambiente');

// Atualiza os HTMLs para incluir o env-config.js
const htmlFiles = [
    'index.html', 'taro2.html', 'login.html', 'dashboard.html',
    'dna.html', 'numerologia.html', 'hawkins.html', 'bovis.html',
    'cursos.html', 'curso-player.html', 'mestres.html'
];

for (const file of htmlFiles) {
    const filePath = path.join(DIST_DIR, file);
    if (!fs.existsSync(filePath)) continue;

    let content = fs.readFileSync(filePath, 'utf-8');

    // Adiciona o script env-config antes de qualquer outro script
    content = content.replace(
        '</head>',
        '    <script src="js/env-config.js"></script>\n</head>'
    );

    // Atualiza cachebusters
    content = content.replace(/\?v=(\d+\.\d+\.\d+)/g, '?v=' + Date.now());

    fs.writeFileSync(filePath, content, 'utf-8');
}

console.log('✅ HTMLs atualizados com env-config.js');
console.log('🚀 Build concluído com sucesso!');